# Generated by Django 5.0.4 on 2024-04-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academica', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carrera',
            new_name='Academica_carrera',
        ),
        migrations.RenameModel(
            old_name='Curso',
            new_name='Academica_curso',
        ),
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Academica_estudiante',
        ),
        migrations.RenameModel(
            old_name='Matricula',
            new_name='Academica_matricula',
        ),
    ]
